name: libmobility
channels:
  - conda-forge
dependencies:
  - cmake >=3.24
  - cuda-version 12.*
  - gxx
  - cuda-libraries-dev
  - cuda-nvcc 
  - make
  - mkl-devel
  - pybind11
  - numpy
  - pytest
  - scipy
